//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ArqueosCajaMetadata))]
    public partial class Arqueos_Caja
    {
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> saldo { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
