//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Caja_ChicaMetadata))]
    public partial class Caja_Chica
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> efectivo_total { get; set; }
        public Nullable<double> billetes { get; set; }
        public Nullable<double> monedas { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
