//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int IDDistrito { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Canton { get; set; }
    
        public virtual Canton Canton1 { get; set; }
    }
}
