//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(IngresoMetadata))]
    public partial class Ingreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingreso()
        {
            this.Detalle_Ingreso = new HashSet<Detalle_Ingreso>();
        }
    
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> monto_total { get; set; }
        public string comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Ingreso> Detalle_Ingreso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
