//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Registro_Inventario_VYCUZEntities : DbContext
    {
        public Registro_Inventario_VYCUZEntities()
            : base("name=Registro_Inventario_VYCUZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arqueos_Caja> Arqueos_Caja { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Caja_Chica> Caja_Chica { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Detalle_Ingreso> Detalle_Ingreso { get; set; }
        public virtual DbSet<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<NotasDeCreditoYDebito> NotasDeCreditoYDebito { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Reparaciones> Reparaciones { get; set; }
        public virtual DbSet<Reportes_Tecnicos> Reportes_Tecnicos { get; set; }
        public virtual DbSet<Resena> Resena { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Servicio_Reparacion> Servicio_Reparacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}
