//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reparaciones()
        {
            this.Reportes_Tecnicos = new HashSet<Reportes_Tecnicos>();
        }
    
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public string telefono { get; set; }
        public Nullable<int> servicio_reparacion_id { get; set; }
        public string descripcion_articulo { get; set; }
        public string descripcion_problema { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> monto_total { get; set; }
        public string entregaestimada { get; set; }
    
        public virtual Servicio_Reparacion Servicio_Reparacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportes_Tecnicos> Reportes_Tecnicos { get; set; }
    }
}
